version: '3'
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    ports:
      - 5055:5055
    volumes:
      - ~/.config/jellyseer:/app/config
    restart: unless-stopped
