services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=Etc/UTC
    volumes:
      - ~/.config:/config
      - ~/Syncthing/media-sync/series:/tv #optional
      - ~/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
