version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.config/homarr/configs:/app/data/configs
      - ~/.config/homarr/icons:/app/public/icons
      - ~/.config/homarr/data:/data
    ports:
      - '7575:7575'
    environment:
      - PUID=1000
      - PGID=1000
