version: "3"
name: "portainer-ce"
services:
  portainer-ce:
      container_name: portainer
      image: portainer/portainer-ce:alpine-sts
      environment:
        - PUID=1000
        - PGID=1000
      ports:
          - 8000:8000
          - 9443:9443
      restart: always
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ~/.config/portainer_data:/data