version: "3"
name: syncthing-server
services:
  syncthing:
    image: syncthing/syncthing:edge
    container_name: syncthing
    hostname: synct-server
    volumes:
      - ~/Syncthing:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
