services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - TZ=Etc/UTC
      #- TRANSMISSION_WEB_HOME= #optional
      #- USER= #optional
      #- PASS= #optional
      #- WHITELIST= #optional
      #- PEERPORT= #optional
      #- HOST_WHITELIST= #optional
    volumes:
      - ~/Syncthing:/syncthing
      - ~/.config:/config
      - ~/Downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
